### ISSUE TITLE
error maxstart = max(genestart)

### ISSUE THREAD

**Issue by S3B-L0P3Z** [kwongj/contig-puller#2]
Hi Jason,
I ran contig-puller on two of my genomes and it prompts an error that did not show before (when I successfully ran it through)

Creating BLAST database ...

Building a new DB, current time: 03/02/2018 16:56:47
New DB name:   /home/sebastian/contig-puller/tempdb/db
New DB title:  /home/sebastian/Desktop/MdtG.fasta
Sequence type: Nucleotide
Keep Linkouts: T
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 1 sequences in 0.000426054 seconds.
--------------------------
Traceback (most recent call last):
  File "contig-puller.py", line 102, in <module>
    maxstart = max(genestart)
ValueError: max() arg is an empty sequence
 

What can this error mean?

Thanks

[problems.zip](https://github.com/kwongj/contig-puller/files/1779921/problems.zip)

**Comment by kwongj** [comment]
I'll look into it over the next week or so.

**Comment by kwongj** [comment]
Sorry for the delay @S3B-L0P3Z .

You're probably getting this error because you don't have any BLAST hits for your `--db MdtG.fasta` in the sequences you're searching. Try setting `--id 90` or lower.

**Comment by kwongj** [comment]
Need to add error message for no BLAST hits

**Comment by kwongj** [comment]
Closed #2.
