### ISSUE TITLE
please provide release tag

### ISSUE THREAD

**Issue by EricDeveaud** [kwongj/contig-puller#3]
Hello, 

I was asked to install contig-puller on our cluster.
our policy is to provide tagged releases for the installed software.

can you provide a release tag ? 

regards

Eric

**Comment by kwongj** [comment]
No problem. Will do this over the next week or so once I fix some bugs.

**Comment by EricDeveaud** [comment]
gentle bump ;-)

**Comment by kwongj** [comment]
@EricDeveaud sorry! should be available now.

Will look to migrate to Python 3 soon too.
